# Generated by Django 6.0.1 on 2026-02-25 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0002_blogs_categories_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
